"""
Integration tests for the Python scraper's profile loading.

Tests that profile.json generated by the web app is correctly
parsed by the Python scraper's load_profile function.

Scenarios:
1. Valid profile with all fields → loads correctly
2. Minimal profile (required fields only) → fills defaults
3. Skills have correct tier mapping
4. Weights are parsed as floats
5. Edge cases: empty arrays, missing optional fields
6. Schema mismatch detection (missing required keys)
7. Cross-system compatibility: web-generated JSON → Python loader
"""

import json

# Import the actual load_profile from scrape.py
import sys
import tempfile
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from scrape import load_profile

# ─── Fixtures ────────────────────────────────────────────────────────────────


def write_profile(data: dict) -> Path:
    """Write a profile dict to a temp JSON file and return the path."""
    tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8")
    json.dump(data, tmp, indent=2)
    tmp.close()
    return Path(tmp.name)


# ─── Fixtures: Profiles ─────────────────────────────────────────────────────


@pytest.fixture
def full_profile() -> dict:
    """A complete profile as generated by the web app wizard."""
    return {
        "skills": [
            {"name": "React", "tier": "core"},
            {"name": "TypeScript", "tier": "core"},
            {"name": "Python", "tier": "strong"},
            {"name": "Django", "tier": "strong"},
            {"name": "Docker", "tier": "peripheral"},
        ],
        "titles": ["Full Stack Developer", "Frontend Engineer"],
        "keywords": ["react", "typescript", "python", "django", "docker"],
        "locations": ["Adelaide", "Sydney", "Melbourne"],
        "roles": [
            "Graduate Developer",
            "Full Stack Developer",
            "Frontend Developer",
        ],
        "weights": {
            "skills": 1.5,
            "companyTier": 0.8,
            "location": 1.2,
            "titleMatch": 1.3,
            "sponsorship": 0.5,
            "recency": 1.0,
            "culture": 1.0,
            "quality": 0.8,
        },
        "minScore": 25,
    }


@pytest.fixture
def minimal_profile() -> dict:
    """Minimum required fields only."""
    return {
        "skills": [{"name": "Python", "tier": "core"}],
        "titles": ["Developer"],
        "keywords": ["python"],
    }


# ─── Tests: Valid profiles ───────────────────────────────────────────────────


class TestLoadProfileValid:
    def test_full_profile_loads_all_fields(self, full_profile):
        path = write_profile(full_profile)
        result = load_profile(path)

        assert len(result["skills"]) == 5
        assert "React" in result["skills"]
        assert len(result["titles"]) == 2
        assert len(result["keywords"]) == 5
        assert len(result["locations"]) == 3
        assert len(result["roles"]) == 3

    def test_skill_tiers_mapped_to_points(self, full_profile):
        path = write_profile(full_profile)
        result = load_profile(path)

        # Core = 5 points, Strong = 3, Peripheral = 1
        tiers = result["skill_tiers"]
        assert tiers["react"] == 5  # core
        assert tiers["typescript"] == 5  # core
        assert tiers["python"] == 3  # strong
        assert tiers["django"] == 3  # strong
        assert tiers["docker"] == 1  # peripheral

    def test_weights_parsed_as_floats(self, full_profile):
        path = write_profile(full_profile)
        result = load_profile(path)

        weights = result["weights"]
        assert weights["skills"] == 1.5
        assert weights["companyTier"] == 0.8
        assert weights["location"] == 1.2
        assert weights["titleMatch"] == 1.3
        assert weights["sponsorship"] == 0.5
        assert isinstance(weights["skills"], float)

    def test_keywords_lowercased(self, full_profile):
        path = write_profile(full_profile)
        result = load_profile(path)

        for kw in result["keywords"]:
            assert kw == kw.lower(), f"Keyword '{kw}' is not lowercase"

    def test_locations_preserved(self, full_profile):
        path = write_profile(full_profile)
        result = load_profile(path)

        assert "Adelaide" in result["locations"]
        assert "Sydney" in result["locations"]
        assert "Melbourne" in result["locations"]


class TestLoadProfileMinimal:
    def test_minimal_profile_fills_defaults(self, minimal_profile):
        path = write_profile(minimal_profile)
        result = load_profile(path)

        assert len(result["skills"]) == 1
        assert len(result["titles"]) == 1
        assert len(result["keywords"]) == 1

        # Should have default locations
        assert len(result["locations"]) > 0

        # Should have default weights (all 1.0)
        for value in result["weights"].values():
            assert value == 1.0

    def test_missing_locations_gets_defaults(self, minimal_profile):
        path = write_profile(minimal_profile)
        result = load_profile(path)

        # Default locations from scrape.py
        assert any("Adelaide" in loc for loc in result["locations"])

    def test_missing_weights_gets_defaults(self, minimal_profile):
        path = write_profile(minimal_profile)
        result = load_profile(path)

        expected_keys = {
            "skills",
            "companyTier",
            "location",
            "titleMatch",
            "sponsorship",
            "recency",
            "culture",
            "quality",
        }
        assert set(result["weights"].keys()) == expected_keys


# ─── Tests: Edge cases ──────────────────────────────────────────────────────


class TestLoadProfileEdgeCases:
    def test_empty_skills_array(self):
        profile = {"skills": [], "titles": ["Dev"], "keywords": ["python"]}
        path = write_profile(profile)
        result = load_profile(path)

        assert result["skills"] == []
        assert result["skill_tiers"] == {}

    def test_duplicate_skills_deduplicated(self):
        profile = {
            "skills": [
                {"name": "React", "tier": "core"},
                {"name": "React", "tier": "strong"},  # Duplicate
                {"name": "react", "tier": "peripheral"},  # Case duplicate
            ],
            "titles": ["Dev"],
            "keywords": ["react"],
        }
        path = write_profile(profile)
        result = load_profile(path)

        # Python deduplicates by lowercase name — only first occurrence kept
        assert result["skills"].count("React") == 1
        assert result["skill_tiers"]["react"] == 5  # First was core = 5

    def test_invalid_tier_defaults_to_peripheral(self):
        profile = {
            "skills": [{"name": "Go", "tier": "expert"}],
            "titles": ["Dev"],
            "keywords": ["go"],
        }
        path = write_profile(profile)
        result = load_profile(path)

        assert result["skill_tiers"]["go"] == 1  # peripheral = 1 point

    def test_skill_as_plain_string(self):
        """Legacy format: skills as plain strings (not objects)."""
        profile = {
            "skills": ["Python", "JavaScript"],
            "titles": ["Dev"],
            "keywords": ["python"],
        }
        path = write_profile(profile)
        result = load_profile(path)

        assert "Python" in result["skills"]
        assert "JavaScript" in result["skills"]
        # Plain strings default to peripheral
        assert result["skill_tiers"]["python"] == 1
        assert result["skill_tiers"]["javascript"] == 1

    def test_special_chars_in_skill_names(self):
        profile = {
            "skills": [
                {"name": "C++", "tier": "core"},
                {"name": "C#", "tier": "strong"},
                {"name": "ASP.NET Core", "tier": "peripheral"},
            ],
            "titles": ["Dev"],
            "keywords": ["c++"],
        }
        path = write_profile(profile)
        result = load_profile(path)

        assert "C++" in result["skills"]
        assert "C#" in result["skills"]
        assert result["skill_tiers"]["c++"] == 5

    def test_weight_zero_means_disabled(self):
        profile = {
            "skills": [{"name": "Python", "tier": "core"}],
            "titles": ["Dev"],
            "keywords": ["python"],
            "weights": {
                "skills": 0,
                "companyTier": 0,
                "location": 0,
                "titleMatch": 0,
                "sponsorship": 0,
                "recency": 0,
                "culture": 0,
                "quality": 0,
            },
        }
        path = write_profile(profile)
        result = load_profile(path)

        for value in result["weights"].values():
            assert value == 0.0

    def test_weight_at_max(self):
        profile = {
            "skills": [{"name": "Python", "tier": "core"}],
            "titles": ["Dev"],
            "keywords": ["python"],
            "weights": {
                "skills": 2.0,
                "companyTier": 2.0,
                "location": 2.0,
                "titleMatch": 2.0,
                "sponsorship": 2.0,
                "recency": 2.0,
                "culture": 2.0,
                "quality": 2.0,
            },
        }
        path = write_profile(profile)
        result = load_profile(path)

        for value in result["weights"].values():
            assert value == 2.0

    def test_empty_skill_name_skipped(self):
        profile = {
            "skills": [
                {"name": "", "tier": "core"},
                {"name": "  ", "tier": "core"},
                {"name": "Valid", "tier": "core"},
            ],
            "titles": ["Dev"],
            "keywords": ["valid"],
        }
        path = write_profile(profile)
        result = load_profile(path)

        assert len(result["skills"]) == 1
        assert result["skills"][0] == "Valid"


# ─── Tests: Schema validation ───────────────────────────────────────────────


class TestLoadProfileSchemaValidation:
    def test_missing_required_key_skills(self):
        profile = {"titles": ["Dev"], "keywords": ["python"]}
        path = write_profile(profile)

        with pytest.raises(ValueError, match="skills"):
            load_profile(path)

    def test_missing_required_key_titles(self):
        profile = {
            "skills": [{"name": "Python", "tier": "core"}],
            "keywords": ["python"],
        }
        path = write_profile(profile)

        with pytest.raises(ValueError, match="titles"):
            load_profile(path)

    def test_missing_required_key_keywords(self):
        profile = {
            "skills": [{"name": "Python", "tier": "core"}],
            "titles": ["Dev"],
        }
        path = write_profile(profile)

        with pytest.raises(ValueError, match="keywords"):
            load_profile(path)

    def test_file_not_found(self):
        with pytest.raises(FileNotFoundError):
            load_profile("/nonexistent/path/profile.json")

    def test_invalid_json(self):
        tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8")
        tmp.write("not valid json {{{")
        tmp.close()

        with pytest.raises(json.JSONDecodeError):
            load_profile(tmp.name)


# ─── Tests: Cross-system compatibility ──────────────────────────────────────


class TestWebToPythonCompatibility:
    """
    Tests that verify the exact JSON format generated by the
    web app wizard is correctly consumed by the Python scraper.
    """

    def test_web_generated_profile_roundtrip(self, full_profile):
        """Simulate: web generates JSON → save to file → Python loads it."""
        # Simulate web app JSON.stringify output
        json_str = json.dumps(full_profile, indent=2)

        # Write it like the web app would
        tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8")
        tmp.write(json_str)
        tmp.close()

        # Python scraper loads it
        result = load_profile(tmp.name)

        # Verify no data loss
        assert len(result["skills"]) == len(full_profile["skills"])
        assert result["titles"] == full_profile["titles"]
        assert result["keywords"] == full_profile["keywords"]
        assert result["locations"] == full_profile["locations"]
        assert result["roles"] == full_profile["roles"]

    def test_web_skip_ai_empty_profile(self):
        """Profile generated by clicking 'Continue without AI' with no skills added."""
        skip_ai_profile = {
            "skills": [],
            "titles": [
                "Software Engineer",
                "Full Stack Developer",
                "Frontend Developer",
            ],
            "keywords": [],
            "locations": ["Adelaide", "Sydney", "Melbourne"],
            "roles": [
                "Software Engineer",
                "Full Stack Developer",
                "Frontend Developer",
            ],
            "weights": {
                "skills": 1,
                "companyTier": 1,
                "location": 1,
                "titleMatch": 1,
                "sponsorship": 1,
                "recency": 1,
                "culture": 1,
                "quality": 1,
            },
            "minScore": 20,
        }
        path = write_profile(skip_ai_profile)
        result = load_profile(path)

        assert result["skills"] == []
        assert len(result["titles"]) == 3
        assert len(result["locations"]) == 3
        assert len(result["roles"]) == 3

    def test_min_score_from_profile(self, full_profile):
        """minScore is now loaded by load_profile."""
        path = write_profile(full_profile)
        result = load_profile(path)
        assert result["min_score"] == 25

    def test_extra_fields_ignored(self, full_profile):
        """Web app may add fields that Python doesn't know about — should be ignored."""
        full_profile["newField"] = "some value"
        full_profile["anotherField"] = [1, 2, 3]
        path = write_profile(full_profile)

        result = load_profile(path)
        assert len(result["skills"]) == 5


# ─── Tests: New profile fields (maxHours, resultsPerSearch, excludeSeniority) ─


class TestNewProfileFields:
    def test_max_hours_loaded(self):
        profile = {
            "skills": [{"name": "Python", "tier": "core"}],
            "titles": ["Dev"],
            "keywords": ["python"],
            "maxHours": 48,
        }
        path = write_profile(profile)
        result = load_profile(path)
        assert result["max_hours"] == 48

    def test_max_hours_default(self, minimal_profile):
        path = write_profile(minimal_profile)
        result = load_profile(path)
        assert result["max_hours"] == 24

    def test_results_per_search_loaded(self):
        profile = {
            "skills": [{"name": "Python", "tier": "core"}],
            "titles": ["Dev"],
            "keywords": ["python"],
            "resultsPerSearch": 50,
        }
        path = write_profile(profile)
        result = load_profile(path)
        assert result["results_per_search"] == 50

    def test_results_per_search_default(self, minimal_profile):
        path = write_profile(minimal_profile)
        result = load_profile(path)
        assert result["results_per_search"] == 20

    def test_exclude_seniority_loaded(self):
        profile = {
            "skills": [{"name": "Python", "tier": "core"}],
            "titles": ["Dev"],
            "keywords": ["python"],
            "excludeSeniority": ["senior", "lead", "staff", "director", "executive"],
        }
        path = write_profile(profile)
        result = load_profile(path)
        assert set(result["exclude_seniority"]) == {
            "senior",
            "lead",
            "staff",
            "director",
            "executive",
        }

    def test_exclude_seniority_default_empty(self, minimal_profile):
        path = write_profile(minimal_profile)
        result = load_profile(path)
        assert result["exclude_seniority"] == []

    def test_min_score_loaded(self):
        profile = {
            "skills": [{"name": "Python", "tier": "core"}],
            "titles": ["Dev"],
            "keywords": ["python"],
            "minScore": 40,
        }
        path = write_profile(profile)
        result = load_profile(path)
        assert result["min_score"] == 40

    def test_min_score_default(self, minimal_profile):
        path = write_profile(minimal_profile)
        result = load_profile(path)
        assert result["min_score"] == 20

    def test_full_profile_with_all_new_fields(self):
        """Profile generated by updated web app with all fields."""
        profile = {
            "skills": [{"name": "React", "tier": "core"}],
            "titles": ["Software Engineer"],
            "keywords": ["react"],
            "locations": ["Adelaide", "Sydney"],
            "roles": ["Software Engineer"],
            "weights": {
                "skills": 1.5,
                "companyTier": 1,
                "location": 1,
                "titleMatch": 1,
                "sponsorship": 1,
                "recency": 1,
                "culture": 1,
                "quality": 1,
            },
            "minScore": 35,
            "maxHours": 24,
            "resultsPerSearch": 20,
            "excludeSeniority": ["senior", "lead", "staff", "director", "executive"],
        }
        path = write_profile(profile)
        result = load_profile(path)

        assert result["max_hours"] == 24
        assert result["results_per_search"] == 20
        assert result["min_score"] == 35
        assert "senior" in result["exclude_seniority"]
        assert result["weights"]["skills"] == 1.5

    def test_invalid_max_hours_uses_default(self):
        profile = {
            "skills": [{"name": "Python", "tier": "core"}],
            "titles": ["Dev"],
            "keywords": ["python"],
            "maxHours": "invalid",
        }
        path = write_profile(profile)
        result = load_profile(path)
        assert result["max_hours"] == 24

    def test_invalid_results_per_search_uses_default(self):
        profile = {
            "skills": [{"name": "Python", "tier": "core"}],
            "titles": ["Dev"],
            "keywords": ["python"],
            "resultsPerSearch": "bad",
        }
        path = write_profile(profile)
        result = load_profile(path)
        assert result["results_per_search"] == 20
